### ISSUE TITLE
Aflter last update not show the product name 

### ISSUE THREAD

**Issue by sirrion1** [nicho92/mkm-api-java#3]
I added new columns to control the stock with EnglishName and the LocationName of the card into StockTableModel

`	private static final String[] columns={"EnglishName","LocationName","Language", "expansion","price","condition","foil","signed","playset","altered","comments","count"};
`
and
`case 0: return a.getProduct().getEnName();
			case 1: return a.getProduct().getLocName();
			case 2: return a.getLanguage().getLanguageName();
			case 3: return a.getProduct().getExpansion();
			case 4: return a.getPrice();
			case 5: return a.getCondition();
			case 6 : return a.isFoil();
			case 7 : return a.isSigned();
			case 8 : return a.isPlayset();
			case 9 : return a.isAltered();
			case 10 : return a.getComments();
			case 11 : return a.getCount();`

**Comment by nicho92** [comment]
use case 0 : return a;
